inputSet:
  name: Build_Oyyou_EphemeralEnvironments_Web_1702467745587-pr-trigger-input-set
  identifier: Build_Oyyou_EphemeralEnvironments_Web_1702467745587prtriggerinputset
  orgIdentifier: default
  projectIdentifier: default_project
  pipeline:
    identifier: Build_Oyyou_EphemeralEnvironments_Web_1702467745587
    properties:
      ci:
        codebase:
          build:
            type: PR
            spec:
              number: <+trigger.prNumber>
