version: '3'

services:
  ee.web:
    labels:
      shipyard.route: '/'
    container_name: "ee-web"
    image: ${DOCKER_REGISTRY-}ee-web
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - ee_net
    expose:
      - 3000
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

networks:
  ee_net:
    external: true